# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, '\u4e0a\u7ebf'), (3, '\u8349\u7a3f')], default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
